#!/bin/bash

if [ "$1" == "create" ]; then
    sqlplus64 "ashincul/04016054@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF

    CREATE TABLE "ASHINCUL"."BENEFITS"
    (	"ID" NUMBER,
	  "BENEFIT_TYPE" VARCHAR2(255 BYTE),
	  "BENEFIT_DETAILS" VARCHAR2(255 BYTE),
	  "BENEFIT_COST" NUMBER(10,2)
    ) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "DBCOURSE" ;

    CREATE TABLE "ASHINCUL"."BONUSES"
    (	"ID" NUMBER,
	  "BONUS_TYPE" VARCHAR2(50 BYTE),
	  "BONUS_AMOUNT" NUMBER(10,2),
	  "SALARY_ID" NUMBER,
	  "HR_MANAGER_ID" VARCHAR2(50 BYTE)
    ) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "DBCOURSE" ;

    CREATE TABLE "ASHINCUL"."EMPLOYEE"
    (	"ID" VARCHAR2(50 BYTE),
	  "NAME" VARCHAR2(255 BYTE),
	  "BANKING_INFO" VARCHAR2(255 BYTE),
	  "HR_MANAGER_ID" VARCHAR2(50 BYTE)
    ) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "DBCOURSE" ;

    CREATE TABLE "ASHINCUL"."EMPLOYEE_TIME_OFF_REQUESTS"
    (	"EMPLOYEE_ID" VARCHAR2(50 BYTE),
	  "TIME_OFF_REQUEST_ID" NUMBER
    ) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "DBCOURSE" ;

    CREATE TABLE "ASHINCUL"."FINAL_PAYMENT"
    (	"TRANSACTION_ID" NUMBER,
	  "NET_PAY" NUMBER(10,2),
	  "SALARY_ID" NUMBER,
	  "EMPLOYEE_ID" VARCHAR2(50 BYTE)
    ) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "DBCOURSE" ;

    CREATE TABLE "ASHINCUL"."FULL_TIME_EMPLOYEE"
    (	"EMPLOYEE_ID" VARCHAR2(50 BYTE),
	  "FIXED_SALARY" NUMBER(10,2)
    ) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "DBCOURSE" ;

    CREATE TABLE "ASHINCUL"."FULL_TIME_EMPLOYEE_BENEFITS"
    (	"FULL_TIME_EMPLOYEE_ID" VARCHAR2(50 BYTE),
	  "BENEFIT_ID" NUMBER
    ) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "DBCOURSE" ;

    CREATE TABLE "ASHINCUL"."HR_MANAGER"
    (	"ID" VARCHAR2(50 BYTE),
	  "PASSWORD" VARCHAR2(255 BYTE)
    ) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "DBCOURSE" ;

    CREATE TABLE "ASHINCUL"."OVERTIME"
    (	"ID" NUMBER,
	  "HOURS" NUMBER(10,2),
	  "RATE_MULTIPLIER" NUMBER(10,2),
	  "SALARY_ID" NUMBER,
	  "HR_MANAGER_ID" VARCHAR2(50 BYTE)
    ) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "DBCOURSE" ;

    CREATE TABLE "ASHINCUL"."PART_TIME_EMPLOYEE"
    (	"EMPLOYEE_ID" VARCHAR2(50 BYTE),
	  "PAY_RATE" NUMBER,
	  "HOURS_WORKED" NUMBER
    ) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "DBCOURSE" ;

    CREATE TABLE "ASHINCUL"."PART_TIME_EMPLOYEE_OVERTIME"
    (	"PART_TIME_EMPLOYEE_ID" VARCHAR2(50 BYTE),
	  "OVERTIME_ID" NUMBER
    ) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "DBCOURSE" ;

    CREATE TABLE "ASHINCUL"."SALARY"
    (	"ID" NUMBER,
	  "GROSS_PAY" NUMBER(10,2),
	  "VACATION_PAY" NUMBER(10,2),
	  "SICK_PAY" NUMBER(10,2)
    ) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "DBCOURSE" ;

    CREATE TABLE "ASHINCUL"."TAXES"
    (	"ID" NUMBER,
	  "EMPLOYMENT_INSURANCE" NUMBER(10,2),
	  "CANADA_PENSION_PLAN" NUMBER(10,2),
	  "PROVINCIAL_TAXES" NUMBER(10,2),
	  "FEDERAL_TAXES" NUMBER(10,2),
	  "FINAL_PAYMENT_ID" NUMBER
    ) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "DBCOURSE" ;

    CREATE TABLE "ASHINCUL"."TIME_OFF_REQUESTS"
    (	"ID" NUMBER,
	  "START_DATE" DATE,
	  "END_DATE" DATE,
	  "STATUS" VARCHAR2(50 BYTE),
	  "HR_MANAGER_ID" VARCHAR2(50 BYTE)
    ) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "DBCOURSE" ;

  EXIT;
EOF
else
    echo "Operation not authorized"
fi
