#!/bin/bash

if [ "$1" == "drop" ]; then
    sqlplus64 "ashincul/07238034@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF

    DROP TABLE "ASHINCUL"."BENEFITS" CASCADE CONSTRAINTS;
    DROP TABLE "ASHINCUL"."BONUSES" CASCADE CONSTRAINTS;
    DROP TABLE "ASHINCUL"."EMPLOYEE" CASCADE CONSTRAINTS;
    DROP TABLE "ASHINCUL"."EMPLOYEE_TIME_OFF_REQUESTS" CASCADE CONSTRAINTS;
    DROP TABLE "ASHINCUL"."FINAL_PAYMENT" CASCADE CONSTRAINTS;
    DROP TABLE "ASHINCUL"."FULL_TIME_EMPLOYEE" CASCADE CONSTRAINTS;
    DROP TABLE "ASHINCUL"."FULL_TIME_EMPLOYEE_BENEFITS" CASCADE CONSTRAINTS;
    DROP TABLE "ASHINCUL"."HR_MANAGER" CASCADE CONSTRAINTS;
    DROP TABLE "ASHINCUL"."OVERTIME" CASCADE CONSTRAINTS;
    DROP TABLE "ASHINCUL"."PART_TIME_EMPLOYEE" CASCADE CONSTRAINTS;
    DROP TABLE "ASHINCUL"."PART_TIME_EMPLOYEE_OVERTIME" CASCADE CONSTRAINTS;
    DROP TABLE "ASHINCUL"."SALARY" CASCADE CONSTRAINTS;
    DROP TABLE "ASHINCUL"."TAXES" CASCADE CONSTRAINTS;
    DROP TABLE "ASHINCUL"."TIME_OFF_REQUESTS" CASCADE CONSTRAINTS;

    EXIT;
EOF
else
    echo "Operation not authorized"
fi
